//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxesV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dossier()
        {
            this.Declarations = new HashSet<Declaration>();
        }
    
        public string NDossier { get; set; }
        public Nullable<System.DateTime> DateDossier { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public string RedevableId { get; set; }
        public string TerrainID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Declaration> Declarations { get; set; }
        public virtual Redevable Redevable { get; set; }
        public virtual Terrain Terrain { get; set; }
    }
}
