//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxesV1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxesV2Entities : DbContext
    {
        public TaxesV2Entities()
            : base("name=TaxesV2Entities")
        {
        }
        public TaxesV2Entities(string UserName,string Password,string Server=".")
            : base($"metadata=res://*/TaxesDataModel.csdl|res://*/TaxesDataModel.ssdl|res://*/TaxesDataModel.msl;provider=System.Data.SqlClient;provider connection string=\"data source={Server};initial catalog=TaxesV2;user id={UserName};password={Password};MultipleActiveResultSets=True;App=EntityFramework\"")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Declaration> Declarations { get; set; }
        public virtual DbSet<Dossier> Dossiers { get; set; }
        public virtual DbSet<Redevable> Redevables { get; set; }
        public virtual DbSet<Terrain> Terrains { get; set; }
        public virtual DbSet<Constant> Constants { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
