//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTNB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration
    {
        public int ID { get; set; }
        public string NDossier { get; set; }
        public System.DateTime DateDeclaration { get; set; }
        public bool Payer { get; set; }
        public int Anne { get; set; }
        public string NQuitance { get; set; }
        public Nullable<int> NAvis { get; set; }
    
        public virtual Dossier Dossier { get; set; }
    }
}
