//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTNB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terrain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terrain()
        {
            this.Dossiers = new HashSet<Dossier>();
        }
    
        public string NTF { get; set; }
        public string Lieu { get; set; }
        public double SuperficeBrute { get; set; }
        public double SuperficeTaxable { get; set; }
        public string Type { get; set; }
        public string Etat { get; set; }
        public Nullable<System.DateTime> DateChangementEtat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dossier> Dossiers { get; set; }
    }
}
